### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by daviddelmonte** [hirokimu/EMTLoadingIndicator#4]
I must be doing something dumb. Please advise. I'm getting a build error on initialization:

```
indicator = EMTLoadingIndicator(interfaceController: self, interfaceImage: image!,
                                        width: 40, height: 40, style: .line)

error: Use of unresolved identifier 'image'
```

Thanks!

**Comment by hirokimu** [comment]
@daviddelmonte Is the "image" variable declared correctly in your code?

**Comment by daviddelmonte** [comment]
I don't understand, sorry.. How should the image variable be declared? Thanks

**Comment by hirokimu** [comment]
@daviddelmonte You need to add some WKInterfaceImage object on the Interface Controller in Storyboard. Then declare IBOutlet variable such as 'image' in its custom class and connect to the above object.

**Comment by daviddelmonte** [comment]
OK. Got it !! Thanks!

On May 27, 2019, at 3:53 PM, Hironobu Kimura <notifications@github.com> wrote:

@daviddelmonte <https://github.com/daviddelmonte> You need to add some WKInterfaceImage object on the Interface Controller in Storyboard. Then declare IBOutlet variable such as 'image' in its custom class and connect to the above object.

**Comment by daviddelmonte** [comment]
Sorry, add-on question. I have the control working. However, how did you make the image take the whole watch window? I want to show the control while I'm downloading info from a web service.

**Comment by hirokimu** [comment]
@daviddelmonte Simply enlarge WKInterfaceImage's size and pass its size to EMTLoadingIndicator's initializer. You need to styling the indicator properly. But the graphic resource files of dot indicator are made for 80x80px size so it is not suitable for larger size.
You can make larger resource files with waitIndicatorGraphic.fla on your own (Flash CC or Animate CC required).

**Comment by daviddelmonte** [comment]
Thanks! it’s brilliant. Works perfectly..

On May 28, 2019, at 1:35 PM, Hironobu Kimura <notifications@github.com> wrote:

@daviddelmonte <https://github.com/daviddelmonte> Simply enlarge WKInterfaceImage's size and pass its size to EMTLoadingIndicator's initializer. You need to styling the indicator properly. But the graphic resource files of dot indicator are made for 80x80px size so it is not suitable for larger size.
You can make larger resource files with waitIndicatorGraphic.fla on your own (Flash CC or Animate CC required).
